name = "backendito"
type = "javascript"
[site]
bucket = "./.next"

account_id = "8103442525fb7d50503fb738fda817e2"


[build]
command = "pnpm build"
output_dir = "out"  # Esta es la carpeta donde Next.js coloca los archivos estáticos cuando haces un 'next export'
pages_build_output_dir = "./out"
upload = { format = "modules" }
