name = "nombre-de-tu-proyecto"
type = "javascript"

# Configura el directorio de tu build de Next.js
[site]
bucket = "./.next"
entry-point = "./"

# Tu cuenta de Cloudflare
account_id = 8103442525fb7d50503fb738fda817e2
